### ISSUE TITLE
Please update your example code

### ISSUE THREAD

**Issue by stretch327** [guangmean/OwnProvider#2]
The port number and URI specified in your example code do not match what is specified in code. They should be:

http://127.0.0.1:27953/ownprovider/inner/push

The payload section should also be URL encoded like this:

%7B%22aps%22:%7B%22alert%22:%22Hello%22%7D%7D

instead of {"aps":{"alert":"Hello"}}

**Comment by guangmean** [comment]
Thanks for pointing out the problem.
curl request has been updated and it can post payload like json string directly without URL encoded.
